W5D1/music_app_testing/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/bands')

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:show, :new, :create] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy,]

  resources :notes, only: [:create, :destroy]
end

W5D1/music_app_testing/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band
  has_many :tracks, dependent: :destroy

  # can't use presence validation with boolean field
  validates :band, :name, :year, presence: true
  validates :live, inclusion: { in: [true, false] }
  validates :name, uniqueness: { scope: :band_id }
  validates :year, numericality: { minimum: 1900, maximum: 9000 }

  after_initialize :set_defaults

  def set_defaults
    self.live ||= false
  end
end

W5D1/music_app_testing/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!
  
  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :live, :name, :year)
  end
end

W5D1/music_app_testing/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5D1/music_app_testing/app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>
<% button_text = album.persisted? ? "Update Album!" : "Create Album!" %>

<form class='form' action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='album-name'>Name</label>
    <input id='album-name' type="text" name="album[name]" value="<%= album.name %>">
  </p>

  <p>
    <label for='album-band'>Band</label>
    <select id='album-band' name="album[band_id]">
        <% Band.all.each do |band| %>
            <option
                <%= "selected" if album.band_id == band.id %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
  </p>

  <p>
    <label for="album_live_t">Live</label>
    <input
      type="radio"
      name="album[live]"
      value="t"
      id="album_live_t"
      <%= "checked" if album.live %>>
    <label for="album_live_f">Studio</label>
    <input
      type="radio"
      name="album[live]"
      value="f"
      id="album_live_f"
      <%= "checked" if !album.live %>>
  </p>

  <p>
    <label for='album-year'>Year</label>
    <input id='album-year' type="number" name="album[year]" value="<%= album.year %>">
  </p>

  <input type="submit" value="<%= button_text %>">
</form>

W5D1/music_app_testing/app/views/albums/edit.html.erb
<h1 class='page-header'>Edit <%= @album.name %></h1>

<%= render "form", album: @album %>

W5D1/music_app_testing/app/views/albums/new.html.erb
<h1 class='page-header'>New <%= @band.name %> Album!</h1>

<%= render "form", album: @album %>

W5D1/music_app_testing/app/views/albums/show.html.erb
<h1 class='page-header'><%= @album.name %></h1>

<% if @album.tracks.length > 0 %>
<ul class='main-list'>
  <% @album.tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><p><%= track.name %></p></a></li>
  <% end %>
</ul>
<% else %>
  <p>This album has no tracks... yet!</p> 
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_album_track_url(@album) %>">New track</a></li>
  <li><a class='button' href="<%= edit_album_url(@album) %>">Edit album</a></li>
  <li>
    <form action="<%= album_url(@album) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Album">
    </form>
  </li>
  <li><a class='button' href="<%= band_url(@album.band) %>">Back to <%= @album.band.name %></a></li>
</ul>