W5D1/music_app_testing/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/bands')

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:show, :new, :create] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy,]

  resources :notes, only: [:create, :destroy]
end

W5D1/music_app_testing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class='main-content'>
      <h1 class='main-logo'>Music App</h1>

      <% if logged_in? %>
        <nav>
          <a class='button' href="<%= bands_url %>">Take me Home</a>
          
          <div class='user-detail'>
            <p>Logged in as: <%= current_user.email %></p>
          <form action=<%= session_url %> method='post'>
            <input
              type="hidden"
              name="_method"
              value="delete">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
            <input 
              type="submit" value="Sign Out">
          </form>
          </div>
        </nav>
      <% end %>

      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:errors] %>
        <p><%= flash[:errors].join(", ") %></p>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>